# Generated by Django 5.2.6 on 2025-11-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='A short bio about yourself.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
