QUOTES = [
    "Traveling – it leaves you speechless, then turns you into a storyteller.",
    "The world is a book, and those who do not travel read only one page.",
    "Adventure may hurt you but monotony will kill you.",
    "Jobs fill your pockets, but adventures fill your soul.",
    "Life is short and the world is wide.",
    "To travel is to live.",
    "Wherever you go becomes a part of you somehow.",
    "Take only memories, leave only footprints.",
    "The journey of a thousand miles begins with a single step.",
    "Travel far enough, you meet yourself.",
    "Once a year, go someplace you’ve never been before.",
    "Not all those who wander are lost.",
    "Fill your life with adventures, not things.",
    "Wander often, wonder always.",
    "Collect moments, not things.",
    "The best views come after the hardest climbs.",
    "Travel makes one modest. You see what a tiny place you occupy in the world.",
    "Oh, the places you’ll go.",
    "Travel is the only thing you buy that makes you richer.",
    "A journey is best measured in friends, rather than miles.",
    "Blessed are the curious for they shall have adventures.",
    "Wherever you go, go with all your heart.",
    "Let’s find some beautiful place to get lost.",
    "We travel not to escape life, but for life not to escape us.",
    "Life begins at the end of your comfort zone.",
    "The biggest adventure you can take is to live the life of your dreams.",
    "You don’t have to be rich to travel well.",
    "It feels good to be lost in the right direction.",
    "Take vacations. You can always make money. You can’t always make memories.",
    "To awaken alone in a strange town is one of the pleasantest sensations in the world.",
    "Travel teaches toleration.",
    "The gladdest moment in human life is a departure into unknown lands.",
    "Travel is the best education.",
    "A good traveler has no fixed plans, and is not intent on arriving.",
    "Travel opens your heart, broadens your mind, and fills your life with stories.",
    "Live your life by a compass, not a clock.",
    "You only live once, but if you do it right, once is enough.",
    "Adventure is worthwhile in itself.",
    "Don’t listen to what they say. Go see.",
    "The goal is to die with memories, not dreams.",
    "Travel sparks our imagination, feeds our curiosity, and reminds us how much we all have in common.",
    "To travel is to discover that everyone is wrong about other countries.",
    "Life is meant for good friends and great adventures.",
    "We have nothing to lose and a world to see.",
    "If not now, when?",
    "A journey is an adventure with a purpose.",
    "There are no foreign lands. It is the traveler only who is foreign."
]
